apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: chat-server
          image: {{ .Values.server.image }}
          ports:
            - containerPort: {{ .Values.server.port }}
          env:
            - name: PORT
              value: {{ .Values.server.port | quote }}
            - name: HOST
              value: {{ .Values.server.host | quote }}
            - name: PGHOST
              value: {{ .Values.server.pghost }}
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
  type: LoadBalancer
